# Form implementation generated from reading ui file 'c:\Users\User\Desktop\projects\Converter Minecraft maps to png\app\interface\view\InfoWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infoWindow(object):
    def setupUi(self, infoWindow):
        infoWindow.setObjectName("infoWindow")
        infoWindow.resize(320, 200)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=infoWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.info.setText("")
        self.info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.closeButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)

        self.retranslateUi(infoWindow)
        QtCore.QMetaObject.connectSlotsByName(infoWindow)

    def retranslateUi(self, infoWindow):
        _translate = QtCore.QCoreApplication.translate
        infoWindow.setWindowTitle(_translate("infoWindow", "Dialog"))
        self.closeButton.setText(_translate("infoWindow", "Close"))
